//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocManagement {
    
    public partial class Status {
        
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.Label lblError;
        protected global::System.Web.UI.WebControls.Label lblHealthScore;
        protected global::System.Web.UI.WebControls.Label lblTotalDocs;
        protected global::System.Web.UI.WebControls.Label lblIndexedDocs;
        protected global::System.Web.UI.WebControls.GridView gvMissingFilters;
        protected global::System.Web.UI.WebControls.GridView gvUnindexedDocs;
    }
}
